name: Build Main Branch
on:
  # push:
  #   branches: 
  #     - 'main'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for accurate version tagging
          fetch-tags: true # Whether to fetch tags, even if fetch-depth > 0.
    
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # - name: Test tagging logic
      #   run: |
      #     npm install -g commit-and-tag-version@12.x
      #     git config user.name "github-actions[bot]"
      #     git config user.email "github-actions[bot]@users.noreply.github.com"

      #     LATEST_COMPONENT_TAG=$(git --no-pager tag --sort=-v:refname --merged $(git rev-parse HEAD) -l "${{ vars.PROJECT_DIRECTORY }}/*.*.*"  | head -n 1)
      #     if [[ -z "$LATEST_COMPONENT_TAG" ]] ; then 
      #       echo "LATEST_COMPONENT_TAG tag doesn't exist. Executing first release" ;
      #     else
      #       echo "LATEST_COMPONENT_TAG: $LATEST_COMPONENT_TAG" ;
      #     fi


      # At this stage, the code has successfully passed the build, security scan, and unit tests.
      # We can now proceed with artifact creation for each environment.
      # The commit-and-tag tool updates the version in package.json based on the latest git tag,
      # following a specific format and commit messages.
      # This update must occur before building the code, since the version from package.json
      # is used both in the application and for tagging the release in git.
      # Technically, I could push to the remote repository at the same step as creating the local tag,
      # but I prefer to have a separate step at the very end of the pipeline. This ensures all build steps
      # are completed successfully before updating the remote repository.

      # Release tag will be incremented based on the commits.  Generally the patch version will be incremented.
      # however for features the minor version is incremented.
      - name: Tag version locally
        run: |
          npm install -g commit-and-tag-version@12.x
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          LATEST_COMPONENT_TAG=$(git --no-pager tag --sort=-v:refname --merged $(git rev-parse HEAD) -l "${{ vars.PROJECT_DIRECTORY }}-*.*.*"  | head -n 1)
          if [[ -z "$LATEST_COMPONENT_TAG" ]] ; then 
            echo "LATEST_COMPONENT_TAG tag doesn't exist. Executing first release" ;
            commit-and-tag-version --first-release -t ${{ vars.APPLICATION_NAME }}- \
             --infile $GITHUB_WORKSPACE/${{ vars.PROJECT_DIRECTORY }}/CHANGELOG.md
          else
            commit-and-tag-version --packageFiles $GITHUB_WORKSPACE/${{ vars.PROJECT_DIRECTORY }}/package.json \
            --bumpFiles $GITHUB_WORKSPACE/${{ vars.PROJECT_DIRECTORY }}/package.json \
            --bumpFiles $GITHUB_WORKSPACE/${{ vars.PROJECT_DIRECTORY }}/package-lock.json \
            -t ${{ vars.APPLICATION_NAME }}-  --infile $GITHUB_WORKSPACE/${{ vars.PROJECT_DIRECTORY }}/CHANGELOG.md              
          fi
        working-directory: ${{ github.workspace }}/${{ vars.PROJECT_DIRECTORY }}

      # - name: Tag version locally
      #   run: |
      #     echo "Fetching all tags from remote repository..."
      #     git fetch --tags

      #     echo "Current tags in the repository:"
      #     git tag --list

      #     npm install -g commit-and-tag-version@12.x
      #     git config user.name "github-actions[bot]"
      #     git config user.email "github-actions[bot]@users.noreply.github.com"

      #     LATEST_COMPONENT_TAG=$(git --no-pager tag --sort=-v:refname --merged $(git rev-parse HEAD) -l "${{ vars.PROJECT_DIRECTORY }}-*.*.*"  | head -n 1)
      #     if [[ -z "$LATEST_COMPONENT_TAG" ]] ; then 
      #       echo "No existing tags found. Executing first release." ;
      #       NEW_TAG=$(commit-and-tag-version --dry-run --first-release -t ${{ vars.APPLICATION_NAME }}- \
      #        --infile $GITHUB_WORKSPACE/${{ vars.PROJECT_DIRECTORY }}/CHANGELOG.md | tail -n 1)
      #     else
      #       echo "Latest component tag: $LATEST_COMPONENT_TAG" ;
      #       NEW_TAG=$(commit-and-tag-version --dry-run --packageFiles $GITHUB_WORKSPACE/${{ vars.PROJECT_DIRECTORY }}/package.json \
      #       --bumpFiles $GITHUB_WORKSPACE/${{ vars.PROJECT_DIRECTORY }}/package.json \
      #       --bumpFiles $GITHUB_WORKSPACE/${{ vars.PROJECT_DIRECTORY }}/package-lock.json \
      #       -t ${{ vars.APPLICATION_NAME }}-  --infile $GITHUB_WORKSPACE/${{ vars.PROJECT_DIRECTORY }}/CHANGELOG.md | tail -n 1)             
      #     fi
      #     echo "New tag to be created: $NEW_TAG"

      - name: See details
        run: |
          echo "Current tags in the repository:"
          git tag --list
          cat $GITHUB_WORKSPACE/${{ vars.PROJECT_DIRECTORY }}/CHANGELOG.md

      - name: Submit tag to remote repository
        run: |
          git describe --tags --abbrev=0
          tagName=$(git describe --tags --abbrev=0)
          versionNumber="${tagName##*-}"
          echo "versionNumber $versionNumber"
