name: Build Dev Branches
on:
  push:
    branches: 
      - 'hotfix/**'
      - 'feature/**'
      - 'bugfix/**'
  workflow_dispatch:
jobs:
  build:
    # This condition skips the job if it's the very first push (branch creation)
    if: github.event.before != '0000000000000000000000000000000000000000'  
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: ./aob-ew-react-demo
    steps:
      # - name: Check if this is the first push (branch creation)
      #   id: check_first_push
      #   run: |
      #     if [ "${{ github.event.before }}" = "0000000000000000000000000000000000000000" ]; then
      #       echo "This is the first push (branch creation). Skipping build."
      #       echo "is_first_push=true" >> $GITHUB_OUTPUT
      #     else
      #       echo "This is not the first push. Proceeding with build."
      #       echo "is_first_push=false" >> $GITHUB_OUTPUT
      # - name: Skip build if it's the first push
      #   if: steps.check_first_push.outputs.is_first_push == 'true'
      #   run: echo "Skipping build for the first push (branch creation)."
      # - name: Continue with build if it's not the first push
      #   if: steps.check_first_push.outputs.is_first_push == 'false'  
      #   run: echo "Continuing with build for subsequent pushes."    

      - name: Debug
        run: |
          echo -e "\033[1;31mError\033[0m"
          echo -e "\033[1;32mOK\033[0m"
          echo -e "\033[1;33mThis is a debug step to check the event payload:\033[0m"
          echo -e "\033[1;33mGetting Id for Git Repositories security namespace:\033[0m"
          echo "Before: ${{ github.event.before }}"
          echo "After: ${{ github.event.after }}"
          echo "Ref: ${{ github.ref }}"
          echo "Repository: ${{ github.repository }}"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci
        working-directory: ./aob-ew-react-demo

      - name: Run Unit Tests
        run: npm run test:once
        working-directory: ./aob-ew-react-demo

      - name: List files in the coverage directory
        run: ls -la ./coverage
        working-directory: ./aob-ew-react-demo

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: always() # Ensures the report is published even if tests fail
        with:
          report_paths: '**/junit.xml'

      - name: Code Coverage Summary
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: '**/cobertura-coverage.xml'
          badge: true
          format: markdown
          output: file

      - name: Add Coverage PR Comment
        run: cat code-coverage-results.markdown >> $GITHUB_STEP_SUMMARY                        