name: Deploy To Lower Environment
run-name: Deploying to ${{ inputs.environment }}
on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        description: 'Target environment'
        type: choice
        options: [SBX, ADT]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'